apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mood-predictor-info
  description: A catalog for the mood-predictor openapi module
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=openai'
spec:
  targets: 
    - mood-predictor-api-component.yaml
    - mood-predictor.yaml