openapi: 3.0.1
servers:
  - url: https://mood-predictor.earth.dekt.io
info:
  title: API definition for mood-predictor
  version: 0.0.8
paths:
  /predict-sentiment{statement_collection}:
    get:
      description: "Predict a sentimnet based on a collection of statements"
      parameters:
      - name: "statement_collection"
        in: path
        description: "collection of text statements to analyze"
        required: true
        schema:
          type: "array"
          items:
            $ref: "#/components/schemas/Statement"
      responses:
        200:
          description: "The collective sentiment based on the provided statements"
          headers:
          content:
            application/json:
              schema:
                type: string
        default:
          description: "error collecting data from predictor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Statement:
      type: object
      required:
        - timestamp
        - statement
      properties:
        timestamp:
          type: string
          format: date-time
        location:
          type: string
        statement:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string