openapi: 3.0.1
servers:
  - url: https://mood-predictor.earth.dekt.io
info:
  title: API definition for mood-predictor
  version: 0.0.8
paths:
  /predict-sentiment{statements}:
    get:
      description: "Predict a sentimnet based on a collection of statements"
      parameters:
      - name: "statements_collection"
        in: path
        description: "collection of text statements to analyze"
        required: true
        schema:
          type: array
      responses:
        200:
          description: "A paged array of all predictor data"
          headers:
            x-next:
              description: "A link to the next page of responses"
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Statements"
        default:
          description: "error collecting data from predictor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Sensor:
      type: object
      required:
        - id
        - team
        - mood
      properties:
        id:
          type: integer
          format: int64
        team:
          type: string
        mood:
          type: string
    Statements:
      type: array
      items:
        $ref: "#/components/schemas/Statements"
    Error:
      type: object
      required:
        - code
        - statement
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string